/**
 * AI Insights Panel - shared component for admin/instructor.
 * Shows AI-generated insights with a mandatory disclaimer.
 */
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import apiClient from '../lib/apiClient'
import { getCurrentUser } from '../lib/auth'

interface AIInsight {
  id: string
  campaign_id: string
  summary: string | null
  sentiment: string | null
  themes: string[] | null
  improvement_areas: string[] | null
  provider_used: string | null
  generated_at: string | null
  human_reviewed: boolean
  disclaimer_acknowledged: boolean
}

const DISCLAIMER =
  'AI-generated insights may be incomplete or inaccurate, regardless of the analysis provider used. ' +
  'These results require human review before any action is taken. ' +
  'Student anonymity is maintained; individual students must not be inferred from this output.'

export default function AIInsightsPanel({ campaignId }: { campaignId: string }) {
  const [showPanel, setShowPanel] = useState(false)
  const [disclaimerRead, setDisclaimerRead] = useState(false)
const user = getCurrentUser()

  const { data: insight, isLoading, error, refetch } = useQuery<AIInsight>({
    queryKey: ['ai-insight', campaignId],
    queryFn: async () => {
      const resp = await apiClient.get<AIInsight>(`/ai-insights/campaigns/${campaignId}`)
      return resp.data
    },
    enabled: showPanel,
    retry: false,
  })

  async function handleTrigger() {
    try {
      await apiClient.post(`/ai-insights/campaigns/${campaignId}/trigger`)
      refetch()
    } catch {
      // handled by error display
    }
  }

  if (!showPanel) {
    return (
      <div style={{ marginTop: '1.5rem', paddingTop: '1rem', borderTop: '1px solid #e5e7eb' }}>
        <button onClick={() => setShowPanel(true)} style={styles.showBtn}>
          View AI Insights
        </button>
      </div>
    )
  }

  return (
    <div style={styles.panel}>
      <h4 style={styles.panelTitle}>AI Insights</h4>

      <div style={styles.disclaimer}>
        <strong>⚠ Disclaimer:</strong> {DISCLAIMER}
      </div>

      {!disclaimerRead && (
        <label style={styles.checkLabel}>
          <input
            type="checkbox"
            onChange={(e) => setDisclaimerRead(e.target.checked)}
            checked={disclaimerRead}
          />
          {' '}I understand this content is AI-generated and requires human review.
        </label>
      )}

      {disclaimerRead && (
        <>
          {isLoading && <p style={styles.muted}>Loading insightsأ¢â‚¬آ¦</p>}
          {error && (
        <div>
          {user?.role === 'admin' ? (
            <>
              <p style={styles.muted}>No AI insights generated yet for this campaign.</p>
              <button onClick={handleTrigger} style={styles.triggerBtn}>Generate AI Insights</button>
            </>
          ) : (
            <p style={styles.muted}>AI insights have not been generated by an administrator yet.</p>
          )}
        </div>
      )}
          {insight && (
            <div style={styles.insightContent}>
              <div style={styles.sentimentRow}>
                <strong>Sentiment:</strong>
                <span style={sentimentBadge(insight.sentiment ?? 'neutral')}>
                  {insight.sentiment ?? 'unknown'}
                </span>
                {insight.human_reviewed && (
                  <span style={{ fontSize: '0.8rem', color: '#065f46', marginLeft: '0.5rem' }}>أ¢إ“â€œ Human reviewed</span>
                )}
              </div>

              {insight.summary && (
                <div style={styles.summaryBlock}>
                  <strong>Summary:</strong>
                  <p style={{ margin: '0.25rem 0 0', color: '#1f2328', fontSize: '0.875rem' }}>{insight.summary}</p>
                </div>
              )}

              {insight.themes && insight.themes.length > 0 && (
                <div style={styles.listBlock}>
                  <strong>Key Themes:</strong>
                  <ul style={styles.list}>
                    {insight.themes.map((t) => <li key={t}>{t}</li>)}
                  </ul>
                </div>
              )}

              {insight.improvement_areas && insight.improvement_areas.length > 0 && (
                <div style={styles.listBlock}>
                  <strong>Suggested Improvements:</strong>
                  <ul style={styles.list}>
                    {insight.improvement_areas.map((a) => <li key={a}>{a}</li>)}
                  </ul>
                </div>
              )}

              <p style={styles.provider}>Provider: {insight.provider_used ?? 'unknown'}</p>
            </div>
          )}
        </>
      )}
    </div>
  )
}

function sentimentBadge(sentiment: string): React.CSSProperties {
  const colors: Record<string, { bg: string; text: string }> = {
    positive: { bg: '#d1fae5', text: '#065f46' },
    neutral: { bg: '#f3f4f6', text: '#6b7280' },
    negative: { bg: '#fee2e2', text: '#991b1b' },
    mixed: { bg: '#fef3c7', text: '#92400e' },
  }
  const c = colors[sentiment] ?? colors.neutral
  return {
    display: 'inline-block',
    padding: '2px 10px',
    borderRadius: '12px',
    fontSize: '0.8rem',
    fontWeight: 600,
    background: c.bg,
    color: c.text,
    marginLeft: '0.5rem',
  }
}

const styles: Record<string, React.CSSProperties> = {
  panel: { marginTop: '1.5rem', paddingTop: '1rem', borderTop: '1px solid #e5e7eb' },
  panelTitle: { margin: '0 0 0.75rem', fontSize: '0.95rem', color: '#1f2328' },
  disclaimer: { background: '#fef3c7', border: '1px solid #f59e0b', borderRadius: '6px', padding: '0.75rem 1rem', fontSize: '0.85rem', color: '#92400e', marginBottom: '0.75rem' },
  checkLabel: { display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.875rem', color: '#1f2328', marginBottom: '1rem', cursor: 'pointer' },
  insightContent: { marginTop: '0.75rem' },
  sentimentRow: { display: 'flex', alignItems: 'center', marginBottom: '0.75rem' },
  summaryBlock: { marginBottom: '0.75rem', fontSize: '0.875rem' },
  listBlock: { marginBottom: '0.75rem', fontSize: '0.875rem' },
  list: { margin: '0.25rem 0 0 1.25rem', padding: 0, color: '#1f2328', fontSize: '0.875rem' },
  provider: { fontSize: '0.75rem', color: '#57606a', marginTop: '0.5rem', fontStyle: 'italic' },
  muted: { color: '#57606a', fontSize: '0.875rem' },
  showBtn: { padding: '0.4rem 1rem', background: 'transparent', border: '1px solid #3b82d4', color: '#3b82d4', borderRadius: '6px', cursor: 'pointer', fontSize: '0.875rem' },
  triggerBtn: { padding: '0.4rem 1rem', background: '#3b82d4', color: '#fff', border: 'none', borderRadius: '6px', cursor: 'pointer', fontSize: '0.875rem', marginTop: '0.5rem' },
}


